spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?serverTimezone=GMT%2B8&useUnicode=true&useSSL=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: root
    hikari:
      maximumPoolSize: 5
      minimumIdle: 5
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000



mybatis:
  typeAliasesPackage: com.rwbi.example.mapper
  mapperLocations: classpath:mapper/*Mapper.xml


logging:
  level:
    com.rwbi.example.mapper: debug